### ISSUE TITLE
seperate concerns of bootstrap process

### ISSUE THREAD

**Issue by gretel** [wa/wahoo#52]
howdy! i don't feel it's a good thing to let the boostrap script of wahoo build fish itself. i see the intended comfort and possible luxury of it... but i also see some downsides.
* hardly portable in it's current way :computer: 
* difficult to maintain if the latter shall be achieved
* type of circular dependeny let something that depends on something else build that first
* considering the availability of `homebrew` and similar the script should check carefully on existing installations and try to use existing toolchains itself (`apt`, `yum`, `homebrew`) - which be difficult to maintain, too
* eventually seperate `bootstrap.sh` in two scripts or so
* have good documentation outlining the various ways of installing fish prior to wahoo
* support solaris, freebsd and windows users! hail POSIX! :cherries:

**Comment by gretel** [comment]
:baby_bottle:

**Comment by bucaran** [comment]
Wahoo does all this because I wanted a complete solution that includes fish. In other words, the script should work for _most_ users. That was an intentional decision.

+ hardly portable in it's current way :computer:

:+1: Let's work on making it more portable.

difficult to maintain if the latter shall be achieved

+ We'll see, I like your idea about splitting things up, but then again, I am OK maintaining one super install script.

+  type of circular dependeny let something that depends on something else build that first
considering the availability of homebrew and similar the script should check carefully on existing installations and try to use existing toolchains itself (apt, yum, homebrew) - which be difficult to maintain, too

Yes. Let's make a list of all the possible existing toolchains and add more checks so that we don't have to install things unnecessarily.


> eventually seperate bootstrap.sh in two scripts or so

Maybe.


> have good documentation outlining the various ways of installing fish prior to wahoo

Sure.


> support solaris, freebsd and windows users! hail POSIX! :cherries:

:+1:

**Comment by s0r00t** [comment]
Maybe bootstrap.sh could be divided in 2 parts :
-A first sh part checking if fish and dependencies are installed.
-A second fish part installing Wahoo.

**Comment by bucaran** [comment]
If we really want to get this feature going we will need a more detail requirement spec. Let's leave this issue open, but give it low priority.

**Comment by gretel** [comment]
i'm going to write specs, because i feel they can be very much re-usable. low-prio is fine in the meantime.
besides, reaching out to all POSIX users is a key motivation for me, perosnally :princess:

**Comment by bucaran** [comment]
:+1:

**Comment by gretel** [comment]
partly related to https://github.com/fish-shell/wahoo/pull/62 - already suffering in terms of communication from the lack of specs

**Comment by bucaran** [comment]
@gretel Well, I went ahead and took a Pontius Pilate approach removing the ability to install git and fish with Wahoo. Now, these two packages are system requirements in order to install Wahoo.

**Comment by gretel** [comment]
:beers:
